import type { 
  Agent, 
  Customer, 
  InventoryItem, 
  Payment, 
  Subscription,
  User 
} from "@shared/schema";

// Mock Users for authentication and system users
export const generateMockUsers = (): Partial<User>[] => [
  {
    id: 1,
    username: "admin",
    firstName: "Admin",
    lastName: "User",
    email: "admin@azamtv.com",
    role: "admin",
  },
  {
    id: 2,
    username: "agent01",
    firstName: "John",
    lastName: "Mwamba",
    email: "john.mwamba@azamtv.com",
    role: "agent",
  },
  {
    id: 3,
    username: "manager01",
    firstName: "Sarah",
    lastName: "Kibwana",
    email: "sarah.kibwana@azamtv.com",
    role: "manager",
  },
  {
    id: 4,
    username: "demo",
    firstName: "Demo",
    lastName: "User",
    email: "demo@azamtv.com",
    role: "demo",
  },
];

export const generateMockAgents = (): Partial<Agent>[] => [
  {
    id: 1,
    title: "Mr",
    firstName: "John",
    lastName: "Mwamba", 
    email: "john.mwamba@azamtv.com",
    phone: "+255 712 345 678",
    mobile: "+255 712 345 678",
    fax: "+255 222 345 678",
    type: "Agent",
    country: "Tanzania",
    region: "Dar es Salaam",
    city: "Dar es Salaam",
    district: "Kinondoni",
    ward: "Msimbazi",
    address1: "Msimbazi Street, Block A, House 123",
    address2: "Near Shoprite",
    postalCode: "14110",
    tinNumber: "123456789",
    vrnNumber: "VRN123456",
    currency: "TSH",
    role: "Sales Agent",
    status: "approved",
    commission: "7.50",
    onboardingRefNo: "AG001-2025",
    kycDocuments: {
      nationalId: "uploaded",
      businessLicense: "uploaded",
      taxCertificate: "uploaded"
    }
  },
  {
    id: 2,
    title: "Ms",
    firstName: "Sarah",
    lastName: "Kibwana",
    email: "sarah.kibwana@azamtv.com", 
    phone: "+255 713 456 789",
    mobile: "+255 713 456 789",
    type: "Agent",
    country: "Tanzania",
    region: "Mwanza",
    city: "Mwanza",
    district: "Nyamagana",
    ward: "Buhongwa",
    address1: "Uhuru Street, Plot 45",
    address2: "",
    postalCode: "33100",
    tinNumber: "987654321",
    vrnNumber: "VRN987654",
    currency: "TSH",
    role: "Technical Support",
    status: "approved",
    commission: "5.00",
    onboardingRefNo: "AG002-2025",
    kycDocuments: {
      nationalId: "uploaded",
      businessLicense: "uploaded",
      taxCertificate: "pending"
    }
  },
  {
    id: 3,
    title: "Mr",
    firstName: "Michael",
    lastName: "Kamau",
    email: "michael.kamau@azamtv.com",
    phone: "+255 714 567 890",
    mobile: "+255 714 567 890",
    type: "Sub Agent",
    country: "Tanzania",
    region: "Arusha",
    city: "Arusha",
    district: "Arusha",
    ward: "Kaloleni",
    address1: "Sokoine Road, House 67",
    address2: "Near Clock Tower",
    postalCode: "23100",
    tinNumber: "456789123",
    vrnNumber: "VRN456789",
    currency: "TSH",
    role: "Field Agent",
    status: "pending",
    commission: "5.00",
    onboardingRefNo: "AG003-2025",
    kycDocuments: {
      nationalId: "uploaded",
      businessLicense: "pending",
      taxCertificate: "pending"
    }
  },
  {
    id: 4,
    title: "Mrs",
    firstName: "Grace",
    lastName: "Mollel",
    email: "grace.mollel@azamtv.com",
    phone: "+255 715 678 901",
    mobile: "+255 715 678 901",
    type: "Agent Employee",
    country: "Tanzania",
    region: "Mbeya",
    city: "Mbeya",
    district: "Mbeya",
    ward: "Iyunga",
    address1: "Mbalizi Road, House 890",
    address2: "",
    postalCode: "53100",
    tinNumber: "789123456",
    vrnNumber: "VRN789123",
    currency: "TSH",
    role: "Customer Service",
    status: "approved",
    commission: "4.50",
    onboardingRefNo: "AG004-2025",
    kycDocuments: {
      nationalId: "uploaded",
      businessLicense: "uploaded",
      taxCertificate: "uploaded"
    }
  },
  {
    id: 5,
    title: "Mr",
    firstName: "Ibrahim",
    lastName: "Hassan",
    email: "ibrahim.hassan@azamtv.com",
    phone: "+255 716 789 012",
    mobile: "+255 716 789 012",
    type: "Installers",
    country: "Tanzania",
    region: "Zanzibar",
    city: "Zanzibar",
    district: "Stone Town",
    ward: "Shaurimoyo",
    address1: "Creek Road, Building 45",
    address2: "Near Forodhani Garden",
    postalCode: "70100",
    tinNumber: "321654987",
    vrnNumber: "VRN321654",
    currency: "TSH",
    role: "Installer",
    status: "approved",
    commission: "6.00",
    onboardingRefNo: "AG005-2025",
    kycDocuments: {
      nationalId: "uploaded",
      businessLicense: "uploaded",
      taxCertificate: "uploaded"
    }
  },
];

export const generateMockCustomers = (): Partial<Customer>[] => [
  {
    id: 1,
    title: "Mr",
    firstName: "Hassan",
    lastName: "Mohamed",
    gender: "Male",
    dateOfBirth: "1985-05-15",
    race: "African",
    phone: "+255 715 123 456",
    mobile: "+255 715 123 456",
    email: "hassan.mohamed@email.com",
    customerType: "Individual",
    serviceType: "DTH",
    accountClass: "Residential",
    connectionType: "Postpaid",
    smsFlag: true,
    addressType: "Installation",
    country: "Tanzania",
    region: "Dar es Salaam",
    city: "Dar es Salaam",
    district: "Kinondoni",
    ward: "Msimbazi",
    address1: "Msimbazi Street, Block A, House 123",
    address2: "Near Shoprite Mall",
    postalCode: "14110",
    tinNumber: "100123456",
    currency: "TSH",
    azamPayId: "PAY123456",
    azamMaxTvId: "AMTV123456",
    onboardingRefNo: "CU001-2025",
    kycDocuments: {
      nationalId: "uploaded",
      proofOfAddress: "uploaded",
      passportPhoto: "uploaded"
    }
  },
  {
    id: 2,
    title: "Ms",
    firstName: "Grace",
    lastName: "Mtembei",
    gender: "Female",
    dateOfBirth: "1992-08-22",
    race: "African",
    phone: "+255 716 234 567",
    mobile: "+255 716 234 567",
    email: "grace.mtembei@email.com",
    orgName: "Mtembei Enterprises Ltd",
    customerType: "Organization",
    serviceType: "DTT",
    accountClass: "Commercial",
    connectionType: "Postpaid",
    smsFlag: true,
    addressType: "Billing",
    country: "Tanzania",
    region: "Mwanza",
    city: "Mwanza",
    district: "Nyamagana",
    ward: "Buhongwa",
    address1: "Uhuru Street, Plot 45",
    address2: "Second Floor",
    postalCode: "33100",
    tinNumber: "200234567",
    vrnNumber: "VRN200234",
    currency: "TSH",
    azamPayId: "PAY234567",
    onboardingRefNo: "CU002-2025",
    kycDocuments: {
      nationalId: "uploaded",
      businessLicense: "uploaded",
      taxCertificate: "uploaded",
      proofOfAddress: "uploaded"
    }
  },
  {
    id: 3,
    title: "Mr",
    firstName: "Peter",
    lastName: "Mollel",
    gender: "Male",
    dateOfBirth: "1978-12-10",
    race: "African",
    phone: "+255 717 345 678",
    mobile: "+255 717 345 678",
    email: "peter.mollel@email.com",
    customerType: "Individual",
    serviceType: "DTH",
    accountClass: "VIP",
    connectionType: "Prepaid",
    smsFlag: true,
    addressType: "Installation",
    country: "Tanzania",
    region: "Arusha",
    city: "Arusha",
    district: "Arusha",
    ward: "Kaloleni",
    address1: "Sokoine Road, House 123",
    address2: "Near Clock Tower",
    postalCode: "23100",
    tinNumber: "300345678",
    currency: "TSH",
    azamPayId: "PAY345678",
    azamMaxTvId: "AMTV345678",
    onboardingRefNo: "CU003-2025",
    kycDocuments: {
      nationalId: "uploaded",
      proofOfAddress: "uploaded",
      passportPhoto: "uploaded"
    }
  },
  {
    id: 4,
    title: "Mrs",
    firstName: "Fatma",
    lastName: "Juma",
    gender: "Female",
    dateOfBirth: "1990-03-18",
    race: "African",
    phone: "+255 718 456 789",
    mobile: "+255 718 456 789",
    email: "fatma.juma@email.com",
    customerType: "Individual",
    serviceType: "OTT",
    accountClass: "Hotels",
    connectionType: "Postpaid",
    smsFlag: true,
    addressType: "Installation",
    country: "Tanzania",
    region: "Zanzibar",
    city: "Zanzibar",
    district: "Stone Town",
    ward: "Shaurimoyo",
    address1: "Creek Road, Building 45",
    address2: "Near Forodhani Garden",
    postalCode: "70100",
    currency: "TSH",
    azamPayId: "PAY456789",
    azamMaxTvId: "AMTV456789",
    onboardingRefNo: "CU004-2025",
    kycDocuments: {
      nationalId: "uploaded",
      proofOfAddress: "uploaded",
      passportPhoto: "uploaded"
    }
  },
  {
    id: 5,
    title: "Dr",
    firstName: "James",
    lastName: "Mwangi",
    gender: "Male",
    dateOfBirth: "1975-07-25",
    race: "African",
    phone: "+255 719 567 890",
    mobile: "+255 719 567 890",
    email: "james.mwangi@email.com",
    orgName: "Mwangi Medical Center",
    customerType: "Organization",
    serviceType: "DTH",
    accountClass: "Corporate",
    connectionType: "Postpaid",
    smsFlag: true,
    addressType: "Billing",
    country: "Tanzania",
    region: "Kilimanjaro",
    city: "Moshi",
    district: "Moshi",
    ward: "Kilimanjaro",
    address1: "Kilimanjaro Avenue, Plot 78",
    address2: "Medical Complex",
    postalCode: "25100",
    tinNumber: "400456789",
    vrnNumber: "VRN400456",
    currency: "TSH",
    azamPayId: "PAY567890",
    onboardingRefNo: "CU005-2025",
    kycDocuments: {
      nationalId: "uploaded",
      businessLicense: "uploaded",
      taxCertificate: "uploaded",
      proofOfAddress: "uploaded"
    }
  },
  {
    id: 6,
    title: "Ms",
    firstName: "Amina",
    lastName: "Said",
    gender: "Female",
    dateOfBirth: "1988-11-02",
    race: "African",
    phone: "+255 720 678 901",
    mobile: "+255 720 678 901",
    email: "amina.said@email.com",
    customerType: "Individual",
    serviceType: "DTT",
    accountClass: "Demo",
    connectionType: "Prepaid",
    smsFlag: false,
    addressType: "Installation",
    country: "Tanzania",
    region: "Mbeya",
    city: "Mbeya",
    district: "Mbeya",
    ward: "Iyunga",
    address1: "Mbalizi Road, House 456",
    address2: "",
    postalCode: "53100",
    currency: "TSH",
    azamPayId: "PAY678901",
    onboardingRefNo: "CU006-2025",
    kycDocuments: {
      nationalId: "uploaded",
      proofOfAddress: "pending",
      passportPhoto: "uploaded"
    }
  },
];

export const generateMockInventory = (): Partial<InventoryItem>[] => [
  {
    id: 1,
    materialCode: "STB-001234",
    serialNumber: "SN123456789",
    type: "Set-Top Box",
    condition: "New",
    status: "available",
    location: "Dar es Salaam Warehouse",
    owner: "AZAM TV",
  },
  {
    id: 2,
    materialCode: "SC-987654", 
    serialNumber: "SN987654321",
    type: "Smart Card",
    condition: "New",
    status: "reserved",
    location: "Dar es Salaam Warehouse",
    owner: "Hassan Mohamed",
  },
  {
    id: 3,
    materialCode: "CBL-456789",
    serialNumber: "SN456789123",
    type: "Cable",
    condition: "New", 
    status: "available",
    location: "Mwanza Branch",
    owner: "AZAM TV",
  },
  {
    id: 4,
    materialCode: "STB-567890",
    serialNumber: "SN567890123",
    type: "Set-Top Box",
    condition: "Refurbished",
    status: "available",
    location: "Arusha Branch",
    owner: "AZAM TV",
  },
  {
    id: 5,
    materialCode: "SC-234567",
    serialNumber: "SN234567890",
    type: "Smart Card",
    condition: "New",
    status: "sold",
    location: "Dar es Salaam Warehouse", 
    owner: "Grace Mtembei",
  },
  {
    id: 6,
    materialCode: "STB-789012",
    serialNumber: "SN789012345",
    type: "Set-Top Box",
    condition: "New",
    status: "transferred",
    location: "Mbeya Branch",
    owner: "AZAM TV",
  },
  {
    id: 7,
    materialCode: "SC-345678",
    serialNumber: "SN345678901",
    type: "Smart Card",
    condition: "Used",
    status: "available",
    location: "Zanzibar Branch",
    owner: "AZAM TV",
  },
  {
    id: 8,
    materialCode: "CBL-678901",
    serialNumber: "SN678901234",
    type: "Cable",
    condition: "New",
    status: "reserved",
    location: "Moshi Branch",
    owner: "Peter Mollel",
  },
  {
    id: 9,
    materialCode: "STB-890123",
    serialNumber: "SN890123456",
    type: "Set-Top Box",
    condition: "Refurbished",
    status: "sold",
    location: "Arusha Branch",
    owner: "Fatma Juma",
  },
  {
    id: 10,
    materialCode: "SC-901234",
    serialNumber: "SN901234567",
    type: "Smart Card",
    condition: "New",
    status: "available",
    location: "Dar es Salaam Warehouse",
    owner: "AZAM TV",
  },
];

export const generateMockPayments = (): Partial<Payment>[] => [
  {
    id: 1,
    customerId: 1,
    amount: "50000.00",
    currency: "TSH",
    paymentMode: "Mobile Money (M-Pesa)",
    referenceNumber: "MP1507252025001",
    type: "hardware",
    status: "completed",
    receiptNumber: "RCP-2025-001",
  },
  {
    id: 2,
    customerId: 2,
    amount: "45000.00",
    currency: "TSH", 
    paymentMode: "Cash",
    referenceNumber: "CASH-2025-001",
    type: "subscription",
    status: "completed",
    receiptNumber: "RCP-2025-002",
  },
  {
    id: 3,
    customerId: 3,
    amount: "65000.00",
    currency: "TSH",
    paymentMode: "Bank Transfer",
    referenceNumber: "BT789123456",
    type: "subscription",
    status: "pending",
    receiptNumber: null,
  },
  {
    id: 4,
    customerId: 4,
    amount: "75000.00",
    currency: "TSH",
    paymentMode: "Mobile Money (Tigo Pesa)",
    referenceNumber: "TP1507252025002",
    type: "hardware",
    status: "completed",
    receiptNumber: "RCP-2025-003",
  },
  {
    id: 5,
    customerId: 5,
    amount: "120000.00",
    currency: "TSH",
    paymentMode: "Bank Transfer",
    referenceNumber: "BT456789123",
    type: "subscription",
    status: "completed",
    receiptNumber: "RCP-2025-004",
  },
  {
    id: 6,
    customerId: 6,
    amount: "25000.00",
    currency: "TSH",
    paymentMode: "Mobile Money (Airtel Money)",
    referenceNumber: "AM1507252025003",
    type: "subscription",
    status: "failed",
    receiptNumber: null,
  },
  {
    id: 7,
    customerId: 1,
    amount: "45000.00",
    currency: "TSH",
    paymentMode: "Mobile Money (M-Pesa)",
    referenceNumber: "MP1507252025004",
    type: "subscription",
    status: "completed",
    receiptNumber: "RCP-2025-005",
  },
  {
    id: 8,
    customerId: 3,
    amount: "35000.00",
    currency: "TSH",
    paymentMode: "Cash",
    referenceNumber: "CASH-2025-002",
    type: "hardware",
    status: "completed",
    receiptNumber: "RCP-2025-006",
  },
];

export const generateMockSubscriptions = (): Partial<Subscription>[] => {
  const today = new Date();
  const nextMonth = new Date(today);
  nextMonth.setMonth(nextMonth.getMonth() + 1);
  
  const lastMonth = new Date(today);
  lastMonth.setMonth(lastMonth.getMonth() - 1);
  
  const threeMonthsAgo = new Date(today);
  threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);
  
  const nextThreeMonths = new Date(today);
  nextThreeMonths.setMonth(nextThreeMonths.getMonth() + 3);

  return [
    {
      id: 1,
      customerId: 1,
      smartCardNumber: "SC-123456789",
      plan: "Premium Package",
      amount: "45000.00",
      startDate: today,
      endDate: nextMonth,
      activationType: "immediate",
      status: "active",
    },
    {
      id: 2,
      customerId: 2,
      smartCardNumber: "SC-987654321", 
      plan: "Basic Package",
      amount: "25000.00",
      startDate: lastMonth,
      endDate: today,
      activationType: "immediate",
      status: "expired",
    },
    {
      id: 3,
      customerId: 3,
      smartCardNumber: "SC-456789123",
      plan: "Family Package",
      amount: "65000.00",
      startDate: today,
      endDate: nextMonth,
      activationType: "scheduled",
      status: "active",
    },
    {
      id: 4,
      customerId: 4,
      smartCardNumber: "SC-789012345",
      plan: "Premium Package",
      amount: "45000.00",
      startDate: today,
      endDate: nextThreeMonths,
      activationType: "immediate",
      status: "active",
    },
    {
      id: 5,
      customerId: 5,
      smartCardNumber: "SC-345678901",
      plan: "Corporate Package",
      amount: "120000.00",
      startDate: threeMonthsAgo,
      endDate: nextThreeMonths,
      activationType: "immediate",
      status: "active",
    },
    {
      id: 6,
      customerId: 6,
      smartCardNumber: "SC-678901234",
      plan: "Basic Package",
      amount: "25000.00",
      startDate: today,
      endDate: nextMonth,
      activationType: "immediate",
      status: "active",
    },
    {
      id: 7,
      customerId: 1,
      smartCardNumber: "SC-901234567",
      plan: "Family Package",
      amount: "65000.00",
      startDate: lastMonth,
      endDate: today,
      activationType: "immediate",
      status: "cancelled",
    },
    {
      id: 8,
      customerId: 3,
      smartCardNumber: "SC-234567890",
      plan: "Premium Package",
      amount: "45000.00",
      startDate: threeMonthsAgo,
      endDate: lastMonth,
      activationType: "immediate",
      status: "expired",
    },
  ];
};

// Additional mock data for dashboard analytics and reports
export const generateMockServiceTypes = () => [
  { name: "DTH (Direct to Home)", customers: 450, percentage: 65 },
  { name: "DTT (Digital Terrestrial)", customers: 200, percentage: 29 },
  { name: "OTT (Azam Max)", customers: 42, percentage: 6 },
];

export const generateMockPackagePlans = () => [
  { name: "Basic Package", price: 25000, subscribers: 180, features: ["20+ channels", "SD quality"] },
  { name: "Premium Package", price: 45000, subscribers: 320, features: ["50+ channels", "HD quality", "Sports channels"] },
  { name: "Family Package", price: 65000, subscribers: 150, features: ["80+ channels", "HD quality", "Kids channels", "Movies"] },
  { name: "Corporate Package", price: 120000, subscribers: 42, features: ["100+ channels", "HD quality", "Business channels", "Multi-screen"] },
];

export const generateMockRegions = () => [
  { name: "Dar es Salaam", customers: 285, agents: 8, revenue: 12750000 },
  { name: "Mwanza", customers: 145, agents: 4, revenue: 6525000 },
  { name: "Arusha", customers: 128, agents: 3, revenue: 5760000 },
  { name: "Mbeya", customers: 89, agents: 2, revenue: 4005000 },
  { name: "Zanzibar", customers: 67, agents: 2, revenue: 3015000 },
  { name: "Kilimanjaro", customers: 78, agents: 2, revenue: 3510000 },
];

export const generateMockSystemMetrics = () => ({
  totalCustomers: 692,
  totalAgents: 21,
  totalRevenue: 35565000,
  activeSubscriptions: 598,
  pendingPayments: 23,
  inventoryItems: 1250,
  systemUptime: 99.8,
  lastUpdated: new Date()
});
